### PR TITLE
Youtube Clone review request

### PR DESCRIPTION
**Pull request by fedgut**

### CODE REVIEW

**Review by Oghenebrume50 — CHANGES_REQUESTED** [review]
Hi team, a very good start on this project :+1: currently the only issue I see is that the iframe shows and works with a different scroll, that should be fixed, the page should have just one scroll like the original. 
While you try to fix that please pay attention to the search field and the button, they are not styled properly, also validate the HTML and fix all errors before submitting for re-review. A little note about the work flow, you should be using GitHub flow for all HTML projects, please take some time to review the pathright requirements to get what it is, and how to properly use it. **cheers**

**Comment by stratospherique** [comment]
Hi Team :clap: , you should be asking a code review on the same pull request that you created the first time. and the reason why is to make the discussion about you project continuous and in the same thread and most importantly, is to merge the code that you committed in a particular Pull Request. Kindly, apply that in the next projects. :wink:

**Review by stratospherique — CHANGES_REQUESTED** [review]
Great Work guys :clinking_glasses:, you're almost done. However, you do need the implement the following requirements:

* [x] Add a describtive README file where you describe the project and add a live preview of your page and show the world the greatness of what you've accomplished. use [githack](https://raw.githack.com/).
* [x] Run your HTML file through [W3C validator](https://validator.w3.org/) and fix the errors that pops out.

Those are tiny bu important changes. Please take care of them and resubmit a code review using this pull request. Great effort :muscle: :muscle:

**Comment by fedgut** [comment]
Validated with [W3 Validator](https://validator.w3.org/#validate_by_upload)
Added info to readme

**Review by Oghenebrume50 — APPROVED** [review]
Looks good guys UI is really nice :+1:, good luck on the next project :wink:

**Pull request merged**
